package Guidesign;

import javax.swing.JFrame;
import controller.Controller;
import javax.swing.JList;

/**
 * Hier kann der Nutzer eine Gästeliste für die ausgewählte Party
 * erstellen. Man kann Gäste aus dem Gästeubch hinzufügen oder entfernen.
 * @author Miri
 */
public class Gaestelisteparty extends JFrame {

    /**
     * Getter für das JList Component der Gästeliste der eingeladenen Gäste.
     * @return gaesteListeEingeladen gibt das JList der Gästeliste der geladenen
     * Gäste zurück.
     */
    public JList<String> getGaesteListeEingeladen() {
        return gaesteListeEingeladen;
    }

    /**
     * Getter für die JList Component der Gästeliste der ungeladenen Gäste.
     * @return gaetseliste gibt das JList der Gästeliste der ungeladenen 
     * Gäste wieder.
     */
    public JList<String> getGaesteListe() {
        return gaestelist;
    }

    /**
     * Erstellt das formular: Gästeliste und die enthaltenen Komponenten. Die
     * Buttons für "Gast hinzufügen" und "Gast entfernen" bekommen einem Action
     * Listener zugewiesen, der im Controller aufgerufen wird
     *
     * @param controller Der {@link Controller} als ActionListener
     */
    public Gaestelisteparty(Controller controller) {
        initComponents();
        gastEntfernen.addActionListener(controller);
        gasthinzufuegen.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton3 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gaestelist = new javax.swing.JList<>();
        gaesteliste = new javax.swing.JLabel();
        gasthinzufuegen = new javax.swing.JButton();
        gastEntfernen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        gaesteListeEingeladen = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton3.setText("jToggleButton3");

        jScrollPane1.setViewportView(gaestelist);

        gaesteliste.setText("Gästeliste");

        gasthinzufuegen.setText("Gast hinzufügen");
        gasthinzufuegen.setActionCommand("Gaestelisteparty.Gast hinzufuegen");

        gastEntfernen.setText("Gast entfernen");
        gastEntfernen.setActionCommand("Gaestelisteparty.Gast entfernen");

        jScrollPane2.setViewportView(gaesteListeEingeladen);

        jLabel1.setText("Geladene Gäste");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gasthinzufuegen, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gastEntfernen, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(gaesteliste)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gaesteliste)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gastEntfernen)
                    .addComponent(gasthinzufuegen))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> gaesteListeEingeladen;
    private javax.swing.JList<String> gaestelist;
    private javax.swing.JLabel gaesteliste;
    private javax.swing.JButton gastEntfernen;
    private javax.swing.JButton gasthinzufuegen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
