package Guidesign;

import controller.Controller;
import javax.swing.JList;

/**
 * Das Gästebuch mit allen eingetragenen Gästen wird angezeigt. Man
 * kann Gäste hinzufügen, bearbeiten(anzeigen) oder löschen.
 * @author Miri
 */
public class Gaestebuch extends javax.swing.JDialog {

    private Controller controller;

    /**
     * Getter für die Gästeliste JList Component.
     * @return gaesteliste: Das JList der Gästeliste.
     */
    public JList<String> getgaesteListe() {
        return gaesteListe;
    }

    /**
     * Erzeugt das Formular für die Gästeliste
     *
     * @param controller Der {@link Controller} wird als Objekt übergeben und zugewiesen
     * und die Koomponenten des Formulars geladen. Action Listener werden
     * hinzugefügt, um die drei Aktionen an den Controller zu übergeben.
     */
    public Gaestebuch(Controller controller) {
        this.controller = controller;
        initComponents();
        addActionListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton3 = new javax.swing.JToggleButton();
        gasthinzufügengb = new javax.swing.JToggleButton();
        gastentfernen = new javax.swing.JToggleButton();
        gastbearbeiten = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gaesteListe = new javax.swing.JList<>();
        gästebuch = new javax.swing.JLabel();

        jToggleButton3.setText("jToggleButton3");

        gasthinzufügengb.setText("Gast hinzufügen");

        gastentfernen.setText("Gast entfernen");

        gastbearbeiten.setText("Gast anzeigen");

        jScrollPane1.setViewportView(gaesteListe);

        gästebuch.setText("Gästebuch");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gasthinzufügengb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gastbearbeiten)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gastentfernen))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(gästebuch)))
                .addGap(278, 278, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(gästebuch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gasthinzufügengb)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gastentfernen)
                        .addComponent(gastbearbeiten)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Die Action Listener für die jeweils belegten Buttons, auf die der
     * Controller reagiert und den betreffenden Code ausführt("speichern,
     * anzeigen oder löschen" als Action Command)
     */
    private void addActionListener() {
        gasthinzufügengb.addActionListener(controller);
        gastentfernen.addActionListener(controller);
        gastbearbeiten.addActionListener(controller);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> gaesteListe;
    private javax.swing.JToggleButton gastbearbeiten;
    private javax.swing.JToggleButton gastentfernen;
    private javax.swing.JToggleButton gasthinzufügengb;
    private javax.swing.JLabel gästebuch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
