package Guidesign;

import controller.Controller;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 * Hier wird ein bereits eingetragener Gast und seine Attribute angezeigt und 
 * man kann diesen gebgebenfalls bearbeiten und speichern.
 * @author Miri
 */
public class GastBearbeiten extends javax.swing.JFrame{

    /**
     * Getter für das JTextField des Vornamen.
     * @return Gibt das JTextField mit dem Vornamen zurück, den der Nutzer 
     * eingegeben hat.
     */
    public JTextField getVnameeintragen() {
        return vnameeintragen;
    }
    
    /**
     * Getter für das JTextField des Nachnamens.
     * @return Gibt das JTextField mit dem Nachnamen zurück, den der Nutzer 
     * eingegeben hat.
     */
    public JTextField getNnameeintragen() {
        return nnameeintragen;
    }
    
    /**
     * Getter für das JTextField der Email.
     * @return Gibt das JTextField der Email zurück, die der Nutzer 
     * eingegeben hat.
     */
    public JTextField getMaileintragen() {
        return maileintragen;
    }
    
    /**
     * Getter für das JTextField des Geburtstags.
     * @return Gibt das JTextField des Geburtstag zurück, den der Nutzer 
     * eingegeben hat.
     */
    public JTextField getGbteintragen() {
        return gbteintragen;
    }
    
    /**
     * Getter für das JTextField der Telefonnummer.
     * @return Gibt das JTextField der Telefonnummer zurück, die der Nutzer 
     * eingegeben hat.
     */
    public JTextField getTeleintragen() {
        return teleintragen;
    }
    
    /**
     * Getter für das JLabel des Errors.
     * @return Gibt das JLabel für die Fehlermeldung zurück, das bei falschen 
     * Benutzeingaben Text anzeigen kann.
     */
    public JLabel getErrorLabel() {
        return errorLabel;
    }
    
    /**
     * Erstellt das Formular GastBearbeiten und fügt dem Button für 
     * "Änderungen speichern" einen Action Listener zu.
     * @param controller Der {@link Controller} als ActionListener
     */
    public GastBearbeiten(Controller controller) {
        initComponents();
        gastspeichern.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gastvname = new javax.swing.JLabel();
        gastnname = new javax.swing.JLabel();
        gastgbt = new javax.swing.JLabel();
        gastmail = new javax.swing.JLabel();
        gasttel = new javax.swing.JLabel();
        vnameeintragen = new javax.swing.JTextField();
        nnameeintragen = new javax.swing.JTextField();
        gbteintragen = new javax.swing.JTextField();
        teleintragen = new javax.swing.JTextField();
        maileintragen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gastspeichern = new javax.swing.JToggleButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        gastvname.setText("Vorname");

        gastnname.setText("Nachname");

        gastgbt.setText("Geburtsdatum");

        gastmail.setText("Email");

        gasttel.setText("Telefon");

        gastspeichern.setText("Änderungen speichern");
        gastspeichern.setActionCommand("bearbeiteter Gast");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gastspeichern)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gastvname)
                            .addComponent(gastnname)
                            .addComponent(gasttel)
                            .addComponent(gastmail)
                            .addComponent(gastgbt))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gbteintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teleintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nnameeintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maileintragen, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vnameeintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(errorLabel)))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {gbteintragen, maileintragen, nnameeintragen, teleintragen, vnameeintragen});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gastvname)
                    .addComponent(vnameeintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gastnname)
                    .addComponent(nnameeintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gastgbt)
                    .addComponent(gbteintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gasttel)
                    .addComponent(teleintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gastmail)
                    .addComponent(maileintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(gastspeichern)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel gastgbt;
    private javax.swing.JLabel gastmail;
    private javax.swing.JLabel gastnname;
    private javax.swing.JToggleButton gastspeichern;
    private javax.swing.JLabel gasttel;
    private javax.swing.JLabel gastvname;
    private javax.swing.JTextField gbteintragen;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField maileintragen;
    private javax.swing.JTextField nnameeintragen;
    private javax.swing.JTextField teleintragen;
    private javax.swing.JTextField vnameeintragen;
    // End of variables declaration//GEN-END:variables
}
