package Guidesign;

/**
 * Hier werden die Tipps und Ideen für eine Kinderparty angezeigt.
 * @author Miri
 */
public class Kinderparty extends javax.swing.JFrame {

    /**
     * Erstellt ein neues Fenster für die Tipps zur Kinderparty.
     */
    public Kinderparty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Starten Sie frühzeitig (ca. 2-3 Monate vorher) mit der Planung!\nSammeln Sie Ideen und lassen Sie sich inspirieren.\n\nLegen Sie das Motto oder das Thema des Kindergeburtstags zusammen mit Ihrem Kind fest.\n\nÜberlegen Sie, wo und wie Sie mit Ihrem Kind feiern möchten. Soll die Party zu \nHause stattfinden, holen Sie sich Unterstützung oder nutzen Sie einen Veranstalter,\nbei dem Sie auswärts die Feier begehen.\n\nEinigen Sie sich auf die Anzahl der Kinder. Als Faustregel gilt – das Geburtstagskind\ndarf so viele Gäste einladen, wie es alt ist (plus/minus ein Kind).\nBei Kindern ab ca. 10 Jahren kommt es auf die Art der Veranstaltung an -\nweniger ist oft mehr!\n\nNehmen Sie Kontakt mit einem Veranstalter oder Animateur für Infos,\nTerminabstimmung und letztlich Buchung auf.\n\nBesorgen Sie Einladungen oder Zubehör und basteln bzw. beschriften diese.\nAm besten ca. 3 Wochen vorher schon verteilen, damit Kinder und Eltern besser \nplanen können.\n\nWerden Dekoartikel oder Spielmaterial benötigt?\nUtensilien dazu rechtzeitig besorgen.\n\nWas soll es zu essen und zu trinken geben? Rezepte aussuchen und Einkaufszettel\nvorbereiten.\n\nKleine Geschenke für Gastkinder besorgen (Mitgebsel-Tüten).\nGeschenkideen für das Geburtstagskind überlegen. In einigen Spielwaren-\nund Buchgeschäften gibt es die Möglichkeit, Geschenkekisten oder –körbe\naufzustellen.\nDort werden vorher die Geschenkwünsche ausgesucht und anschließend können\nFreunde und Verwandte gezielt einen Wunsch erfüllen. \n\nBenötigen Sie noch Helfer oder Autofahrer? Ältere Geschwister freuen sich,\neine Aufgabe übernehmen zu dürfen. Eltern von eingeladenen Kindern finden sich\nbestimmt, die eine Hin- oder Rückfahrt zum Veranstaltungsort übernehmen.\n");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Kinderparty");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
