/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Guidesign;

import controller.Controller;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Sandra
 */
public class Partyerstellen extends javax.swing.JFrame {
    private Controller controller;
    
    public JComboBox getpartyKategorien() {
        return partyKategorien;
    }
    
    public JTextField getpartyname() {
       return partyname;
    }
    
    public JTextField getpartydatum() {
        return partydatum;
    }
    
    public JTextField getpartybudget() {
        return partybudget;
    }
    
    /**
     * Creates new form Partyerstellen
     */
    public Partyerstellen(Controller controller) {
        this.controller = controller;
        initComponents();
        addActionListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        partyKategorien = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        partyname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        partydatum = new javax.swing.JTextField();
        partybudget = new javax.swing.JTextField();
        neuePartyAbbrechen = new javax.swing.JButton();
        neuePartyErstellen = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        partyKategorien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bitte wählen", "Kinderparty", "Couchparty", "Tanzparty" }));

        jLabel1.setText("Partykategorie");

        partyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partynameActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel4.setText("Datum");

        jLabel5.setText("Budget");

        partydatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partydatumActionPerformed(evt);
            }
        });

        neuePartyAbbrechen.setText("Abbrechen");
        neuePartyAbbrechen.setActionCommand("PartyErstellen.Abbrechen");

        neuePartyErstellen.setText("Speichern");
        neuePartyErstellen.setActionCommand("PartyErstellen.Speichern");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(neuePartyAbbrechen)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(errorLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(partybudget)
                                    .addComponent(partydatum)
                                    .addComponent(partyname)
                                    .addComponent(neuePartyErstellen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(partyKategorien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(137, 137, 137))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(partyKategorien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(partyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(partydatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(partybudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neuePartyAbbrechen)
                    .addComponent(neuePartyErstellen))
                .addGap(18, 18, 18)
                .addComponent(errorLabel)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void partynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partynameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partynameActionPerformed

    private void partydatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partydatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partydatumActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton neuePartyAbbrechen;
    private javax.swing.JButton neuePartyErstellen;
    private javax.swing.JComboBox<String> partyKategorien;
    private javax.swing.JTextField partybudget;
    private javax.swing.JTextField partydatum;
    private javax.swing.JTextField partyname;
    // End of variables declaration//GEN-END:variables

    private void addActionListener() {
        neuePartyAbbrechen.addActionListener(controller);
        neuePartyErstellen.addActionListener(controller);
    }
}
