/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Guidesign;

import controller.Controller;
import javax.swing.JTextField;

/**
 *
 * @author Miri
 */
public class Startseite extends javax.swing.JFrame {

    private final Controller controller;

    public JTextField getPartynameeintragen() {
        return partynameeintragen;
    }
    
    public JTextField getPartydatumeintragen() {
        return partydatumeintragen;
    }
    
    public JTextField getPartybudget() {
        return partybudget;
    }
    
    public JTextField getGaesteAnzahlEintragen() {
        return gaesteanzahleintragen;
    }

    /**
     * Creates new form NewJFrame
     */
    public Startseite(Controller controller) {
        this.controller = controller;
        initComponents();
        addActionListeners();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu3 = new javax.swing.JMenu();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        partyname = new javax.swing.JLabel();
        partydatum = new javax.swing.JLabel();
        gaesteanzahl = new javax.swing.JLabel();
        budget = new javax.swing.JLabel();
        anmerkung = new javax.swing.JLabel();
        partynameeintragen = new javax.swing.JTextField();
        partydatumeintragen = new javax.swing.JTextField();
        gaesteanzahleintragen = new javax.swing.JTextField();
        partybudget = new javax.swing.JTextField();
        anermkungeintragen = new javax.swing.JTextField();
        gaestelisteerstellen = new javax.swing.JToggleButton();
        einkaufslisteerstellen = new javax.swing.JToggleButton();
        raumbedarfberechnung = new javax.swing.JToggleButton();
        raumbedarf = new javax.swing.JTextField();
        partyabbrechen = new javax.swing.JToggleButton();
        partyEinfügen = new javax.swing.JToggleButton();
        errorLabel = new javax.swing.JLabel();
        startmenue = new javax.swing.JMenuBar();
        partymenue = new javax.swing.JMenu();
        partyanzeigen = new javax.swing.JMenuItem();
        partyerstellen = new javax.swing.JMenuItem();
        gaestebuchmenue = new javax.swing.JMenu();
        warenlistemenue = new javax.swing.JMenu();
        tipps = new javax.swing.JMenu();
        kinderparty = new javax.swing.JMenuItem();
        couchparty = new javax.swing.JMenuItem();
        tanzparty = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        partyname.setText("Name");

        partydatum.setText("Datum");

        gaesteanzahl.setText("Gästeanzahl");

        budget.setText("Budget");

        anmerkung.setText("Anmerkung");

        gaesteanzahleintragen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaesteanzahlintragenActionPerformed(evt);
            }
        });

        gaestelisteerstellen.setText("Gästeliste erstellen");
        gaestelisteerstellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaestelisteerstellenActionPerformed(evt);
            }
        });

        einkaufslisteerstellen.setText("Einkaufsliste erstellen");
        einkaufslisteerstellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                einkaufslisteerstellenActionPerformed(evt);
            }
        });

        raumbedarfberechnung.setText("Raumbedarf berechnen");
        raumbedarfberechnung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raumbedarfberechnungActionPerformed(evt);
            }
        });

        raumbedarf.setText("qm");
        raumbedarf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raumbedarfActionPerformed(evt);
            }
        });

        partyabbrechen.setText("abbrechen");
        partyabbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partyabbrechenActionPerformed(evt);
            }
        });

        partyEinfügen.setText("speichern");
        partyEinfügen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partyEinfügenActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(partyname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(partydatum, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(gaesteanzahl, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(budget, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(anmerkung, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(partynameeintragen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(partydatumeintragen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(gaesteanzahleintragen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(partybudget, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(anermkungeintragen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(gaestelisteerstellen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(einkaufslisteerstellen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(raumbedarfberechnung, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(raumbedarf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(partyabbrechen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(partyEinfügen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(errorLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(anmerkung)
                                .addGap(18, 18, 18)
                                .addComponent(anermkungeintragen, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(partyname)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(partynameeintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(partydatum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(partydatumeintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(gaesteanzahl)
                                        .addGap(18, 18, 18)
                                        .addComponent(gaesteanzahleintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addComponent(budget)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(partybudget, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(raumbedarfberechnung)
                                            .addComponent(einkaufslisteerstellen)
                                            .addComponent(gaestelisteerstellen)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(raumbedarf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))))))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(partyabbrechen)
                        .addGap(18, 18, 18)
                        .addComponent(partyEinfügen))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {gaesteanzahleintragen, partybudget, partydatumeintragen, partynameeintragen});

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {einkaufslisteerstellen, gaestelisteerstellen, raumbedarfberechnung});

        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partyname)
                    .addComponent(partynameeintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gaestelisteerstellen))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partydatum)
                    .addComponent(partydatumeintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(einkaufslisteerstellen))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gaesteanzahl)
                    .addComponent(gaesteanzahleintragen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raumbedarfberechnung))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(budget)
                    .addComponent(partybudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raumbedarf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anmerkung)
                    .addComponent(anermkungeintragen, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partyabbrechen)
                    .addComponent(partyEinfügen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        partymenue.setText("Party");

        partyanzeigen.setText("Party anzeigen");
        partymenue.add(partyanzeigen);

        partyerstellen.setText("Party erstellen");
        partymenue.add(partyerstellen);

        startmenue.add(partymenue);

        gaestebuchmenue.setText("Gästebuch");
        gaestebuchmenue.setActionCommand("Gaestebuch");
        gaestebuchmenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gaestebuchmenueActionPerformed(evt);
            }
        });
        startmenue.add(gaestebuchmenue);

        warenlistemenue.setText("Warenliste");
        warenlistemenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warenlistemenueActionPerformed(evt);
            }
        });
        startmenue.add(warenlistemenue);

        tipps.setText("Tipps");

        kinderparty.setText("Kinderparty");
        kinderparty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kinderpartyActionPerformed(evt);
            }
        });
        tipps.add(kinderparty);

        couchparty.setText("Couchparty");
        couchparty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couchpartyActionPerformed(evt);
            }
        });
        tipps.add(couchparty);

        tanzparty.setText("Tanzparty");
        tanzparty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanzpartyActionPerformed(evt);
            }
        });
        tipps.add(tanzparty);

        startmenue.add(tipps);

        setJMenuBar(startmenue);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gaesteanzahlintragenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaesteanzahlintragenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gaesteanzahlintragenActionPerformed

    private void raumbedarfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raumbedarfActionPerformed
        // Int anzahl von den angegeben Gästen einlesen, i * 1,5 = Wert W, Ausgabe w
    }//GEN-LAST:event_raumbedarfActionPerformed

    private void gaestelisteerstellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaestelisteerstellenActionPerformed
        Gaestelisteparty g = new Gaestelisteparty();
        g.setVisible(true);
    }//GEN-LAST:event_gaestelisteerstellenActionPerformed

    private void einkaufslisteerstellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_einkaufslisteerstellenActionPerformed
         Einkaufslistefürparty e = new Einkaufslistefürparty();
            e.setVisible(true);            
    }//GEN-LAST:event_einkaufslisteerstellenActionPerformed

    private void raumbedarfberechnungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raumbedarfberechnungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raumbedarfberechnungActionPerformed

    private void partyabbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partyabbrechenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partyabbrechenActionPerformed

    private void gaestebuchmenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gaestebuchmenueActionPerformed
        Gästebuch gb = new Gästebuch();
        gb.setVisible(true);// Menü in Item ändern 
    }//GEN-LAST:event_gaestebuchmenueActionPerformed

    private void warenlistemenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warenlistemenueActionPerformed
      Warenliste wl = new Warenliste();
      wl.setVisible(true);//Menü in Item ändern
    }//GEN-LAST:event_warenlistemenueActionPerformed

    private void kinderpartyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kinderpartyActionPerformed
        Kinderparty kp = new Kinderparty();
        kp.setVisible(true);
    }//GEN-LAST:event_kinderpartyActionPerformed

    private void tanzpartyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanzpartyActionPerformed
        Tanzparty tp = new Tanzparty ();
        tp.setVisible(true);
    }//GEN-LAST:event_tanzpartyActionPerformed

    private void couchpartyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couchpartyActionPerformed
        Couchparty cp = new Couchparty ();
        cp.setVisible(true);
    }//GEN-LAST:event_couchpartyActionPerformed

    private void partyEinfügenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partyEinfügenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partyEinfügenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anermkungeintragen;
    private javax.swing.JLabel anmerkung;
    private javax.swing.JLabel budget;
    private javax.swing.JMenuItem couchparty;
    private javax.swing.JToggleButton einkaufslisteerstellen;
    public javax.swing.JLabel errorLabel;
    private javax.swing.JLabel gaesteanzahl;
    private javax.swing.JTextField gaesteanzahleintragen;
    private javax.swing.JMenu gaestebuchmenue;
    private javax.swing.JToggleButton gaestelisteerstellen;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem kinderparty;
    private javax.swing.JToggleButton partyEinfügen;
    private javax.swing.JToggleButton partyabbrechen;
    private javax.swing.JMenuItem partyanzeigen;
    private javax.swing.JTextField partybudget;
    private javax.swing.JLabel partydatum;
    private javax.swing.JTextField partydatumeintragen;
    private javax.swing.JMenuItem partyerstellen;
    private javax.swing.JMenu partymenue;
    private javax.swing.JLabel partyname;
    private javax.swing.JTextField partynameeintragen;
    private javax.swing.JTextField raumbedarf;
    private javax.swing.JToggleButton raumbedarfberechnung;
    private javax.swing.JMenuBar startmenue;
    private javax.swing.JMenuItem tanzparty;
    private javax.swing.JMenu tipps;
    private javax.swing.JMenu warenlistemenue;
    // End of variables declaration//GEN-END:variables

    private void addActionListeners() {
        this.partyerstellen.addActionListener(controller);
        this.partyanzeigen.addActionListener(controller);
        this.partyEinfügen.addActionListener(controller);
        this.gaestebuchmenue.addActionListener(controller);
        
    }
}
